# Generated by Django 5.2.5 on 2025-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('year_left', models.IntegerField()),
                ('statement', models.CharField(max_length=4095)),
                ('static_img_path', models.CharField(max_length=255, null='')),
            ],
        ),
    ]
