# Generated by Django 5.2.3 on 2025-06-21 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffshift',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='staffshift',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='repeat_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffshift',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StaffShiftException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.staffshift')),
            ],
            options={
                'unique_together': {('shift', 'date')},
            },
        ),
    ]
